language: ruby

rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - rbx

script:
  - bundle install
  - cd test/dummy
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - cd ../..
  - appraisal install
  - appraisal rake test
