language: ruby
cache: bundler
sudo: false

rvm:
  - "2.3.8"
  - "2.4.5"
  - "2.5.3"
  - "2.6.1"
  - "ruby-head"

gemfile:
  - gemfiles/rails_4.2.11.gemfile
  - gemfiles/rails_5.1.6.1.gemfile
  - gemfiles/rails_5.2.2.gemfile
  - gemfiles/rails_6.0.0.beta1.gemfile


matrix:
  allow_failures:
    - rvm: "ruby-head"
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.0.0.beta1.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6.0.0.beta1.gemfile

before_script:
  - gem install bundler
  - bundle install
  - cd test/dummy
  - bundle exec rake db:create db:schema:load RAILS_ENV=test --trace
  - cd ../..

script:
  - bundle exec rake test
