language: ruby
cache: bundler
sudo: false

rvm:
  - "2.3.8"
  - "2.4.5"
  - "2.5.3"
  - "2.6.1"
  - "ruby-head"

matrix:
  allow_failures:
    - rvm: "ruby-head"

before_script:
  - gem install bundler
  - bundle exec appraisal install
  - cd test/dummy
  - bundle exec rake db:create db:schema:load RAILS_ENV=test --trace
  - bundle exec rake db:environment:set RAILS_ENV=test --trace
  - cd ../..

script:
  - bundle exec appraisal rake test
