language: ruby
cache: bundler
sudo: false

rvm:
  - "2.3.8"
  - "2.4.5"
  - "2.5.3"
  - "ruby-head"

matrix:
  allow_failures:
    - rvm: "ruby-head"

before_install:
  - gem install bundler

before_script:
  - appraisal install
  - cd test/dummy
  - RAILS_ENV=test bundle exec rake db:create db:schema:load db:environment:set --trace
  - cd ../..

script:
  - appraisal rake test
